import React, { createContext, useContext, useState } from 'react';
import { LanguageCode } from '../types';

export interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    brand_subtitle: 'Smart Flood & Weather Early Warning',
    home: 'Home',
    live_map: 'Live Risk Map',
    alerts: 'Alerts',
    forecast: 'Forecast',
    resources: 'Resources Portal',
    digital_twin: 'Village Digital Twin',
    history: 'Historical Validation',
    admin: 'Authority Control',
    about_us: 'About Us',
    citizen_mode: 'Citizen Mode',
    authority_mode: 'Authority Dashboard',
    sos_button: 'SOS Emergency',
    system_operational: 'System Operational',
    high_risk_areas: 'High-Risk Areas',
    active_alerts: 'Active Alerts',
    view_live_risk: 'View Live Risk Map',
    predict_prepare_protect: 'Predict. Prepare. Protect.',
    search_location_placeholder: 'Search Indian city, village or state...',
    check_risk: 'Check Your Risk',
    find_shelter: 'Find Safe Shelter',
    plan_evacuation: 'Plan Evacuation Route',
    report_hazard: 'Report a Hazard',
    hero_title: 'Predict. Prepare. Protect. Flash Flood Early Warning System',
    hero_subtitle: 'AI-powered multi-source platform for real-time flash flood prediction, early warning, evacuation routing, and emergency management in hilly regions.',
    live_status: 'LIVE SYSTEM STATUS',
    rainfall: 'Rainfall',
    river_level: 'River Level',
    soil_moisture: 'Soil Moisture',
    current_risk: 'Current Risk',
    danger_near_you: 'DANGER NEAR YOU',
    nearest_shelter: 'Nearest Safe Shelter',
    recommended_route: 'Recommended Evacuation Route',
    navigate_shelter: 'Navigate to Safe Shelter',
    download_report: 'Download Forecast Report (PDF)',
    broadcast_alert: 'Broadcast Emergency Alert',
    digital_twin_heading: 'Village Infrastructure Digital Twin & Flood Simulation',
    history_heading: 'Historical Flood Timeline & AI Backtest Validation',
  },
  hi: {
    brand_subtitle: 'स्मार्ट बाढ़ और मौसम चेतावनी प्रणाली',
    home: 'होम',
    live_map: 'लाइव जोखिम नक्शा',
    alerts: 'अलर्ट',
    forecast: 'पूर्वानुमान',
    resources: 'संसाधन पोर्टल',
    digital_twin: 'ग्राम डिजिटल ट्विन',
    history: 'ऐतिहासिक सत्यापन',
    admin: 'प्राधिकरण नियंत्रण',
    about_us: 'हमारे बारे में',
    citizen_mode: 'नागरिक मोड',
    authority_mode: 'प्राधिकरण डैशबोर्ड',
    sos_button: 'एसओएस आपातकाल',
    system_operational: 'प्रणाली कार्यशील है',
    high_risk_areas: 'उच्च जोखिम वाले क्षेत्र',
    active_alerts: 'सक्रिय अलर्ट',
    view_live_risk: 'लाइव जोखिम नक्शा देखें',
    predict_prepare_protect: 'पूर्वानुमान। तैयारी। सुरक्षा।',
    search_location_placeholder: 'भारतीय शहर, गांव या राज्य खोजें...',
    check_risk: 'अपना जोखिम जांचें',
    find_shelter: 'सुरक्षित आश्रय खोजें',
    plan_evacuation: 'निकासी मार्ग योजना',
    report_hazard: 'खतरे की सूचना दें',
    hero_title: 'पूर्वानुमान। तैयारी। सुरक्षा। आकस्मिक बाढ़ चेतावनी प्रणाली',
    hero_subtitle: 'पहाड़ी क्षेत्रों में वास्तविक समय में आकस्मिक बाढ़ का पूर्वानुमान, चेतावनी, सुरक्षित निकासी और आपातकालीन प्रबंधन प्रणाली।',
    live_status: 'लाइव सिस्टम स्थिति',
    rainfall: 'वर्षा',
    river_level: 'नदी का जलस्तर',
    soil_moisture: 'मृदा नमी',
    current_risk: 'वर्तमान जोखिम',
    danger_near_you: 'आपके पास खतरा है',
    nearest_shelter: 'निकटतम सुरक्षित आश्रय',
    recommended_route: 'अनुशंसित सुरक्षित निकासी मार्ग',
    navigate_shelter: 'सुरक्षित आश्रय की ओर बढ़ें',
    download_report: 'पूर्वानुमान रिपोर्ट डाउनलोड करें (PDF)',
    broadcast_alert: 'आपातकालीन अलर्ट जारी करें',
    digital_twin_heading: 'ग्राम बुनियादी ढांचा डिजिटल ट्विन और बाढ़ सिमुलेशन',
    history_heading: 'ऐतिहासिक बाढ़ समयरेखा और एआई मॉडल सत्यापन',
  },
  bn: {
    brand_subtitle: 'স্মার্ট বন্যা ও আবহাওয়া পূর্বাভাস ব্যবস্থা',
    home: 'হোম',
    live_map: 'লাইভ ঝুঁকি ম্যাপ',
    alerts: 'সতর্কতা',
    forecast: 'পূর্বাভাস',
    resources: 'সম্পদ পোর্টাল',
    digital_twin: 'গ্রাম ডিজিটাল টুইন',
    history: 'ঐতিহাসিক যাচাইকরণ',
    admin: 'প্রশাসন নিয়ন্ত্রণ',
    about_us: 'আমাদের কথা',
    citizen_mode: 'নাগরিক মোড',
    authority_mode: 'প্রশাসন ড্যাশবোর্ড',
    sos_button: 'জরুরি এসওএস',
    system_operational: 'সিস্টেম সক্রিয়',
    high_risk_areas: 'উচ্চ ঝুঁকিপূর্ণ এলাকা',
    active_alerts: 'সক্রিয় সতর্কতা',
    view_live_risk: 'লাইভ ঝুঁকি ম্যাপ দেখুন',
    predict_prepare_protect: 'পূর্বাভাস। প্রস্তুতি। সুরক্ষা।',
    search_location_placeholder: 'ভারতীয় শহর, গ্রাম বা রাজ্য খুঁজুন...',
    check_risk: 'ঝুঁকি পরীক্ষা করুন',
    find_shelter: 'নিরাপদ আশ্রয় খুঁজুন',
    plan_evacuation: 'স্থানান্তর রুট পরিকল্পনা',
    report_hazard: 'বিপদ রিপোর্ট করুন',
    hero_title: 'পূর্বাভাস। প্রস্তুতি। সুরক্ষা। আকস্মিক বন্যা পূর্বাভাস ব্যবস্থা',
    hero_subtitle: 'পাহাড়ী অঞ্চলে রিয়েল-টাইম আকস্মিক বন্যা পূর্বাভাস এবং জরুরি ব্যবস্থাপনা ব্যবস্থা।',
    live_status: 'লাইভ সিস্টেম স্ট্যাটাস',
    rainfall: 'বৃষ্টিপাত',
    river_level: 'নদীর জলস্তর',
    soil_moisture: 'মাটির আর্দ্রতা',
    current_risk: 'বর্তমান ঝুঁকি',
    danger_near_you: 'আপনার কাছাকাছি বিপদ',
    nearest_shelter: 'নিকটতম নিরাপদ আশ্রয়',
    recommended_route: 'সুপারিশকৃত স্থানান্তর পথ',
    navigate_shelter: 'নিরাপদ আশ্রয়ে যান',
    download_report: 'পূর্বাভাস রিপোর্ট ডাউনলোড করুন (PDF)',
    broadcast_alert: 'জরুরি সতর্কতা জারি করুন',
    digital_twin_heading: 'গ্রামের অবকাঠামো ডিজিটাল টুইন ও বন্যা সিমুলেশন',
    history_heading: 'ঐতিহাসিক বন্যা সময়রেখা ও এআই মডেল ব্যাকটেস্ট',
  },
  ta: {
    brand_subtitle: 'ஸ்மார்ட் வெள்ள & வானிலை எச்சரிக்கை அமைப்பு',
    home: 'முகப்பு',
    live_map: 'நேரலை வரைபடம்',
    alerts: 'எச்சரிக்கைகள்',
    forecast: 'முன்னறிவிப்பு',
    resources: 'வளங்கள் மையம்',
    digital_twin: 'கிராம டிஜிட்டல் ட்வின்',
    history: 'வரலாற்று சரிபார்ப்பு',
    admin: 'நிர்வாகக் கட்டுப்பாடு',
    about_us: 'எங்களைப் பற்றி',
    citizen_mode: 'குடிமகன் பயன்முறை',
    authority_mode: 'அதிகாரப்பூர்வ டாஷ்போர்டு',
    sos_button: 'அவசர SOS',
    system_operational: 'அமைப்பு செயல்படுகிறது',
    high_risk_areas: 'அதிக ஆபத்துள்ள பகுதிகள்',
    active_alerts: 'செயலில் உள்ள எச்சரிக்கைகள்',
    view_live_risk: 'நேரலை ஆபத்து வரைபடத்தைப் பார்க்கவும்',
    predict_prepare_protect: 'கணித்தல். தயார்படுத்தல். பாதுகாத்தல்.',
    search_location_placeholder: 'இந்திய நகரம், கிராமம் அல்லது மாநிலத்தைத் தேடுங்கள்...',
    check_risk: 'ஆபத்தைச் சரிபார்க்கவும்',
    find_shelter: 'பாதுகாப்பான புகலிடத்தைக் கண்டறியவும்',
    plan_evacuation: 'வெளியேற்றப் பாதையைத் திட்டமிடுங்கள்',
    report_hazard: 'ஆபத்தைப் புகாரளிக்கவும்',
    hero_title: 'கணித்தல். தயார்படுத்தல். பாதுகாத்தல். வெள்ள எச்சரிக்கை அமைப்பு',
    hero_subtitle: 'மலைப் பகுதிகளில் நிகழ்நேர திடீர் வெள்ளக் கணிப்பு மற்றும் அவசரகால மேலாண்மை அமைப்பு.',
    live_status: 'நேரலை அமைப்பின் நிலை',
    rainfall: 'மழைப்பொழிவு',
    river_level: 'ஆற்றின் நீர்மட்டம்',
    soil_moisture: 'மண் ஈரம்',
    current_risk: 'தற்போதைய ஆபத்து',
    danger_near_you: 'உங்களுக்கு அருகில் ஆபத்து',
    nearest_shelter: 'அருகிலுள்ள பாதுகாப்பான புகலிடம்',
    recommended_route: 'பரிந்துரைக்கப்பட்ட பாதுகாப்பான பாதை',
    navigate_shelter: 'புகலிடத்திற்குச் செல்லவும்',
    download_report: 'அறிக்கையைப் பதிவிறக்குக (PDF)',
    broadcast_alert: 'அவசர எச்சரிக்கை விடுங்கள்',
    digital_twin_heading: 'கிராமக் கூட்டமைப்பு டிஜிட்டல் ட்வின் மற்றும் வெள்ள மாதிரி',
    history_heading: 'வரலாற்று வெள்ளக் காலவரிசை மற்றும் AI மாதிரி சோதனை',
  },
  te: {
    brand_subtitle: 'స్మార్ట్ వరద మరియు వాతావరణ హెచ్చరిక వ్యవస్థ',
    home: 'హోమ్',
    live_map: 'లైవ్ ప్రమాద మ్యాప్',
    alerts: 'హెచ్చరికలు',
    forecast: 'అంచనా',
    resources: 'వనరుల పోర్టల్',
    digital_twin: 'విలేజ్ డిజిటల్ ట్విన్',
    history: 'చారిత్రక ధృవీకరణ',
    admin: 'అధికారిక నియంత్రణ',
    about_us: 'మా గురించి',
    citizen_mode: 'పౌర మోడ్',
    authority_mode: 'అధికారిక డాష్‌బోర్డ్',
    sos_button: 'అత్యవసర SOS',
    system_operational: 'వ్యవస్థ పనిచేస్తోంది',
    high_risk_areas: 'అధిక ప్రమాద ప్రాంతాలు',
    active_alerts: 'సక్రియ హెచ్చరికలు',
    view_live_risk: 'లైవ్ ప్రమాద మ్యాప్‌ను చూడండి',
    predict_prepare_protect: 'అంచనా వేయండి. సిద్ధం చేయండి. రక్షించండి.',
    search_location_placeholder: 'భారతీయ నగరం, గ్రామం లేదా రాష్ట్రాన్ని శోధించండి...',
    check_risk: 'మీ ప్రమాదాన్ని తనిఖీ చేయండి',
    find_shelter: 'సురక్షిత ఆశ్రయాన్ని కనుగొనండి',
    plan_evacuation: 'తరలింపు మార్గాన్ని ప్లాన్ చేయండి',
    report_hazard: 'ప్రమాదాన్ని నివేదించండి',
    hero_title: 'అంచనా. సిద్ధం. రక్షణ. ఆకస్మిక వరద హెచ్చరిక వ్యవస్థ',
    hero_subtitle: 'కొండ ప్రాంతాలలో నిజ-సమయ ఆకస్మిక వరద అంచనా మరియు అత్యవసర నిర్వహణ వ్యవస్థ.',
    live_status: 'లైవ్ సిస్టమ్ స్థితి',
    rainfall: 'వర్షపాతం',
    river_level: 'నది నీటిమట్టం',
    soil_moisture: 'నేల తేమ',
    current_risk: 'ప్రస్తుత ప్రమాదం',
    danger_near_you: 'మీకు దగ్గరలో ప్రమాదం',
    nearest_shelter: 'దగ్గరలోని సురక్షిత ఆశ్రయం',
    recommended_route: 'సిఫార్సు చేసిన సురక్షిత మార్గం',
    navigate_shelter: 'సురక్షిత ఆశ్రయానికి వెళ్లండి',
    download_report: 'అంచనా నివేదికను డౌన్‌లోడ్ చేయండి (PDF)',
    broadcast_alert: 'అత్యవసర హెచ్చరిక జారీ చేయండి',
    digital_twin_heading: 'గ్రామ మౌలిక సదుపాయాల డిజిటల్ ట్విన్ మరియు వరద సిమ్యులేషన్',
    history_heading: 'చారిత్రక వరద కాలక్రమం మరియు AI మోడల్ మూల్యాంకనం',
  },
  mr: {
    brand_subtitle: 'स्मार्ट पूर आणि हवामान पूर्वसूचना प्रणाली',
    home: 'मुख्यपृष्ठ',
    live_map: 'थेट धोका नकाशा',
    alerts: 'इशारे',
    forecast: 'अंदाज',
    resources: 'संसाधने पोर्टल',
    digital_twin: 'डिजिटल ट्विन',
    history: 'ऐतिहासिक पडताळणी',
    admin: 'प्रशासन नियंत्रण',
    about_us: 'आमच्याबद्दल',
    citizen_mode: 'नागरिक मोड',
    authority_mode: 'प्राधिकरण डॅशबोर्ड',
    sos_button: 'आणीबाणी SOS',
    system_operational: 'प्रणाली कार्यरत आहे',
    high_risk_areas: 'उच्च धोक्याचे भाग',
    active_alerts: 'सक्रिय इशारे',
    view_live_risk: 'थेट धोका नकाशा पहा',
    predict_prepare_protect: 'अंदाज. तयारी. संरक्षण.',
    search_location_placeholder: 'भारतीय शहर, गाव किंवा राज्य शोधा...',
    check_risk: 'तुमचा धोका तपासा',
    find_shelter: 'सुरक्षित निवारा शोधा',
    plan_evacuation: 'स्थलांतर मार्ग योजना',
    report_hazard: 'धोक्याची नोंद करा',
    hero_title: 'अंदाज. तयारी. संरक्षण. अचानक पूर इशारा प्रणाली',
    hero_subtitle: 'डोंगराळ भागात रिअल-टाइम अचानक पूर अंदाज, इशारे आणि आणीबाणी व्यवस्थापन.',
    live_status: 'थेट प्रणाली स्थिती',
    rainfall: 'पर्जन्यमान',
    river_level: 'नदीची पातळी',
    soil_moisture: 'मातीचा ओलावा',
    current_risk: 'सध्याचा धोका',
    danger_near_you: 'तुमच्याजवळ धोका आहे',
    nearest_shelter: 'जवळचा सुरक्षित निवारा',
    recommended_route: 'शिफारस केलेला सुरक्षित स्थलांतर मार्ग',
    navigate_shelter: 'सुरक्षित निवार्याकडे जा',
    download_report: 'अंदाज अहवाल डाउनलोड करा (PDF)',
    broadcast_alert: 'आणीबाणीचा इशारा द्या',
    digital_twin_heading: 'गाव पायाभूत सुविधा डिजिटल ट्विन आणि पूर सिम्युलेशन',
    history_heading: 'ऐतिहासिक पूर कालरेखा आणि AI मॉडेल पडताळणी',
  },
  gu: {
    brand_subtitle: 'સ્માર્ટ પૂર અને હવામાન ચેતવણી સિસ્ટમ',
    home: 'હોમ',
    live_map: 'લાઇવ જોખમ નકશો',
    alerts: 'ચેતવણીઓ',
    forecast: 'આગાહી',
    resources: 'સંસાધનો પોર્ટલ',
    digital_twin: 'ગામડું ડિજિટલ ટ્વિન',
    history: 'ઐતિહાસિક ચકાસણી',
    admin: 'વહીવટી નિયંત્રણ',
    about_us: 'અમારા વિશે',
    citizen_mode: 'નાગરિક મોડ',
    authority_mode: 'સત્તાવાર ડેશબોર્ડ',
    sos_button: 'ઇમરજન્સી SOS',
    system_operational: 'સિસ્ટમ કાર્યરત છે',
    high_risk_areas: 'ઉચ્ચ જોખમ ધરાવતા વિસ્તારો',
    active_alerts: 'સક્રિય ચેતવણીઓ',
    view_live_risk: 'લાઇવ જોખમ નકશો જુઓ',
    predict_prepare_protect: 'આગાહી. તૈયારી. રક્ષણ.',
    search_location_placeholder: 'ભારતીય શહેર, ગામ અથવા રાજ્ય શોધો...',
    check_risk: 'તમારું જોખમ તપાસો',
    find_shelter: 'સુરક્ષિત આશ્રય શોધો',
    plan_evacuation: 'સ્થળાંતર માર્ગ આયોજન',
    report_hazard: 'જોખમની જાણ કરો',
    hero_title: 'આગાહી. તૈયારી. રક્ષણ. ઓચિંતા પૂરની ચેતવણી સિસ્ટમ',
    hero_subtitle: 'પહાડી વિસ્તારોમાં રીઅલ-ટાઇમ ઓચિંતા પૂરની આગાહી અને કટોકટી વ્યવસ્થાપન સિસ્ટમ.',
    live_status: 'લાઇવ સિસ્ટમ સ્થિતિ',
    rainfall: 'વરસાદ',
    river_level: 'નદીનું સ્તર',
    soil_moisture: 'જમીનનો ભેજ',
    current_risk: 'વર્તમાન જોખમ',
    danger_near_you: 'તમારી નજીક જોખમ',
    nearest_shelter: 'નજીકનું સુરક્ષિત આશ્રયસ્થાન',
    recommended_route: 'ભલામણ કરેલ સુરક્ષિત માર્ગ',
    navigate_shelter: 'સુરક્ષિત આશ્રયસ્થાન પર જાઓ',
    download_report: 'આગાહી રિપોર્ટ ડાઉનલોડ કરો (PDF)',
    broadcast_alert: 'ઇમરજન્સી એલર્ટ જાહેર કરો',
    digital_twin_heading: 'ગામડાની માળખાકીય સુવિધાઓ ડિજિટલ ટ્વિન અને પૂર સિમ્યુલેશન',
    history_heading: 'ઐતિહાસિક પૂર સમયરેખા અને AI મોડેલ ચકાસણી',
  },
  as: {
    brand_subtitle: 'স্মাৰ্ট বানপানী আৰু বতৰৰ আগতীয়া সতৰ্কবাণী প্ৰণালী',
    home: 'গৃহ',
    live_map: 'লাইভ বিপদাশংকা মানচিত্ৰ',
    alerts: 'সতৰ্কবাণী',
    forecast: 'পূৰ্বানুমূলক সূচী',
    resources: 'সম্পদ প’ৰ্টেল',
    digital_twin: 'গাঁৱৰ ডিজিটেল টুইন',
    history: 'ঐতিহাসিক পৰীক্ষণ',
    admin: 'প্ৰশাসন নিয়ন্ত্ৰণ',
    about_us: 'আমাৰ বিষয়ে',
    citizen_mode: 'নাগৰিক মোড',
    authority_mode: 'প্ৰাধিকৰণ ডেশ্ববৰ্ড',
    sos_button: 'জৰুৰীকালীন SOS',
    system_operational: 'ব্যৱস্থা সক্ৰিয় হৈ আছে',
    high_risk_areas: 'উচ্চ বিপদাশংকা এলেকা',
    active_alerts: 'সক্ৰিয় সতৰ্কবাণী',
    view_live_risk: 'লাইভ বিপদাশংকা মানচিত্ৰ চাওক',
    predict_prepare_protect: 'পূৰ্বানুমোদন। প্ৰস্তুতি। সুৰক্ষা।',
    search_location_placeholder: 'ভাৰতীয় চহৰ, গাঁও বা ৰাজ্য বিচাৰক...',
    check_risk: 'আপোনাৰ বিপদ পৰীক্ষা কৰক',
    find_shelter: 'সুৰক্ষিত আশ্ৰয় বিচাৰক',
    plan_evacuation: 'স্থানান্তৰ পথ পৰিকল্পনা',
    report_hazard: 'বিপদৰ খবৰ দিয়ক',
    hero_title: 'পূৰ্বানুমোদন। প্ৰস্তুতি। সুৰক্ষা। আকস্মিক বানপানীৰ আগতীয়া সতৰ্কবাণী প্ৰণালী',
    hero_subtitle: ' পাহাৰীয়া অঞ্চলত সময়োপযোগী বানপানীৰ পূৰ্বানুমোদন আৰু জৰুৰীকালীন ব্যৱস্থাপনা।',
    live_status: 'লাইভ ব্যৱস্থাৰ স্থিতি',
    rainfall: 'বৃষ্টিপাত',
    river_level: 'নদীৰ পানীৰ স্তৰ',
    soil_moisture: 'মাটিৰ আৰ্দ্ৰতা',
    current_risk: 'বৰ্তমানৰ বিপদ',
    danger_near_you: 'আপোনাৰ কাষত বিপদ',
    nearest_shelter: 'নিকটতম সুৰক্ষিত আশ্ৰয়',
    recommended_route: 'সুপাৰিশ কৰা সুৰক্ষিত পথ',
    navigate_shelter: 'সুৰক্ষিত আশ্ৰয়লৈ যাওক',
    download_report: 'পূৰ্বানুমোদন প্ৰতিবেদন ডাউনলোড কৰক (PDF)',
    broadcast_alert: 'জৰুৰীকালীন সতৰ্কবাণী প্ৰচাৰ কৰক',
    digital_twin_heading: 'গাঁৱৰ আন্তঃগাঁথনি ডিজিটেল টুইন আৰু বানপানী ছিমুলেচন',
    history_heading: 'ঐতিহাসিক বানপানীৰ সময়ৰেখা আৰু AI আৰ্হি পৰীক্ষণ',
  },
  kn: {
    brand_subtitle: 'స్మార్ట్ ఫ్లడ్ & వేదర్ ఎర్లీ వార్నింగ్ సిస్టమ్',
    home: 'ಹೋಮ್',
    live_map: 'ಲೈವ್ ಅಪಾಯದ ನಕ್ಷೆ',
    alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    forecast: 'ಮುನ್ಸೂಚನೆ',
    resources: 'ಸಂಪನ್ಮೂಲಗಳ ಪೋರ್ಟಲ್',
    digital_twin: 'ಡಿಜಿಟಲ್ ಟ್ವಿನ್',
    history: 'ಐತಿಹಾಸಿಕ ಪರಿಶೀಲನೆ',
    admin: 'ಆಡಳಿತ ನಿಯಂತ್ರಣ',
    about_us: 'ನಮ್ಮ ಬಗ್ಗೆ',
    citizen_mode: 'ನಾಗರಿಕ ಮೋಡ್',
    authority_mode: 'ಅಧಿಕೃತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    sos_button: 'ತುರ್ತು SOS',
    system_operational: 'ಸಿಸ್ಟಮ್ ಚಾಲನೆಯಲ್ಲಿದೆ',
    high_risk_areas: 'ಹೆಚ್ಚಿನ ಅಪಾಯದ ಪ್ರದೇಶಗಳು',
    active_alerts: 'ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು',
    view_live_risk: 'ಲೈವ್ ಅಪಾಯದ ನಕ್ಷೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
    predict_prepare_protect: 'ಮುನ್ಸೂಚನೆ. ತಯಾರಿ. ರಕ್ಷಣೆ.',
    search_location_placeholder: 'ಭಾರತೀಯ ನಗರ, ಹಳ್ಳಿ ಅಥವಾ ರಾಜ್ಯವನ್ನು ಹುಡುಕಿ...',
    check_risk: 'ನಿಮ್ಮ ಅಪಾಯವನ್ನು ಪರಿಶೀಲಿಸಿ',
    find_shelter: 'ಸುರಕ್ಷಿತ ಆಶ್ರಯವನ್ನು ಹುಡುಕಿ',
    plan_evacuation: 'ಸ್ಥಳಾಂತರ ಮಾರ್ಗ ಯೋಜನೆ',
    report_hazard: 'ಅಪಾಯವನ್ನು ವರದಿ ಮಾಡಿ',
    hero_title: 'ಮುನ್ಸೂಚನೆ. ತಯಾರಿ. ರಕ್ಷಣೆ. ಹಠಾತ್ ಪ್ರವಾಹ ಎಚ್ಚರಿಕೆ ವ್ಯವಸ್ಥೆ',
    hero_subtitle: 'ಗುಡ್ಡಗಾಡು ಪ್ರದೇಶಗಳಲ್ಲಿ ನೈಜ-ಸಮಯದ ಹಠಾತ್ ಪ್ರವಾಹ ಮುನ್ಸೂಚನೆ ಮತ್ತು ತುರ್ತು ನಿರ್ವಹಣೆ.',
    live_status: 'ಲೈವ್ ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ',
    rainfall: 'ಮಳೆ ಪ್ರಮಾಣ',
    river_level: 'ನದಿಯ ನೀರಿನ ಮಟ್ಟ',
    soil_moisture: 'ಮಣ್ಣಿನ ತೇವಾಂಶ',
    current_risk: 'ಪ್ರಸ್ತುತ ಅಪಾಯ',
    danger_near_you: 'ನಿಮ್ಮ ಬಳಿ ಅಪಾಯವಿದೆ',
    nearest_shelter: 'ಹತ್ತಿರದ ಸುರಕ್ಷಿತ ಆಶ್ರಯ',
    recommended_route: 'ಶಿಫಾರಸು ಮಾಡಿದ ಸುರಕ್ಷಿತ ಮಾರ್ಗ',
    navigate_shelter: 'ಸುರಕ್ಷಿತ ಆಶ್ರಯಕ್ಕೆ ತೆರಳಿ',
    download_report: 'ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (PDF)',
    broadcast_alert: 'ತುರ್ತು ಎಚ್ಚರಿಕೆ ನೀಡಿ',
    digital_twin_heading: 'ಹಳ್ಳಿಯ ಮೂಲಸೌಕರ್ಯ ಡಿಜಿಟಲ್ ಟ್ವಿನ್ ಮತ್ತು ಪ್ರವಾಹ ಸಿಮ್ಯುಲೇಶನ್',
    history_heading: 'ಐತಿಹಾಸಿಕ ಪ್ರವಾಹ ಕಾಲಾವಧಿ ಮತ್ತು AI ಮಾದರಿ ಮೌಲ್ಯಮಾಪನ',
  },
  ml: {
    brand_subtitle: 'സ്മാർട്ട് പ്രളയ വ കാലാവസ്ഥ മുന്നറിയിപ്പ് സംവിധാനം',
    home: 'ഹോം',
    live_map: 'ലൈവ് അപായ മാപ്പ്',
    alerts: 'മുന്നറിയിപ്പുകൾ',
    forecast: 'പ്രവചനം',
    resources: 'വിഭവ പോർട്ടൽ',
    digital_twin: 'ഗ്രാമ ഡിജിറ്റൽ ട്വിൻ',
    history: 'ചരിത്രപരമായ പരിശോധന',
    admin: 'അതോറിറ്റി നിയന്ത്രണം',
    about_us: 'ഞങ്ങളെക്കുറിച്ച്',
    citizen_mode: 'സിറ്റിസൺ മോഡ്',
    authority_mode: 'അതോറിറ്റി ഡാഷ്‌ബോർഡ്',
    sos_button: 'അടിയന്തര SOS',
    system_operational: 'സിസ്റ്റം സജീവമാണ്',
    high_risk_areas: 'ഉയർന്ന അപകടസാധ്യതയുള്ള പ്രദേശങ്ങൾ',
    active_alerts: 'സജീവ മുന്നറിയിപ്പുകൾ',
    view_live_risk: 'ലൈവ് അപായ മാപ്പ് കാണുക',
    predict_prepare_protect: 'പ്രവചിക്കുക. തയ്യാറാവുക. സംരക്ഷിക്കുക.',
    search_location_placeholder: 'ഇന്ത്യൻ നഗരം, ഗ്രാമം അല്ലെങ്കിൽ സംസ്ഥാനം തിരയുക...',
    check_risk: 'നിങ്ങളുടെ അപായസാധ്യത പരിശോധിക്കുക',
    find_shelter: 'സുരക്ഷിത അഭയകേന്ദ്രം കണ്ടെത്തുക',
    plan_evacuation: 'ഒഴിപ്പിക്കൽ പാത പ്ലാൻ ചെയ്യുക',
    report_hazard: 'അപകടം റിപ്പോർട്ട് ചെയ്യുക',
    hero_title: 'പ്രവചിക്കുക. തയ്യാറാവുക. സംരക്ഷിക്കുക. പെട്ടെന്നുള്ള പ്രളയ മുന്നറിയിപ്പ് സംവിധാനം',
    hero_subtitle: 'മലയോര മേഖലകളിൽ തത്സമയ പ്രളയ പ്രവചനവും അടിയന്തര ദുരന്ത നിവാരണ സംവിധാനവും.',
    live_status: 'തത്സമയ സിസ്റ്റം അവസ്ഥ',
    rainfall: 'മഴയുടെ അളവ്',
    river_level: 'നദിയിലെ ജലനിരപ്പ്',
    soil_moisture: 'മണ്ണിന്റെ ഈർപ്പം',
    current_risk: 'നിലവിലെ അപകടസാധ്യത',
    danger_near_you: 'നിങ്ങൾക്ക് സമീപം അപകടസാധ്യത',
    nearest_shelter: 'ഏറ്റവും അടുത്തുള്ള സുരക്ഷിത അഭയകേന്ദ്രം',
    recommended_route: 'നിർദ്ദേശിച്ച സുരക്ഷിത പാത',
    navigate_shelter: 'അഭയകേന്ദ്രത്തിലേക്ക് പോകുക',
    download_report: 'പ്രവചന റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക (PDF)',
    broadcast_alert: 'അടിയന്തര മുന്നറിയിപ്പ് നൽകുക',
    digital_twin_heading: 'ഗ്രാമിക അടിസ്ഥാന സൗകര്യ ഡിജിറ്റൽ ട്വിൻ & പ്രളയ സിമുലേഷൻ',
    history_heading: 'ചരിത്രപരമായ പ്രളയ സമയരേഖയും AI മോഡൽ പരിശോധനയും',
  },
  pa: {
    brand_subtitle: 'ਸਮਾਰਟ ਹੜ੍ਹ ਅਤੇ ਮੌਸਮ ਚੇਤਾਵਨੀ ਪ੍ਰਣਾਲੀ',
    home: 'ਹੋਮ',
    live_map: 'ਲਾਈਵ ਖਤਰਾ ਨਕਸ਼ਾ',
    alerts: 'ਚੇਤਾਵਨੀਆਂ',
    forecast: 'ਭਵਿੱਖਬਾਣੀ',
    resources: 'ਸਰੋਤ ਪੋਰਟਲ',
    digital_twin: 'ਪਿੰਡ ਡਿਜੀਟਲ ਟਵਿਨ',
    history: 'ਇਤਿਹਾਸਕ ਜਾਂਚ',
    admin: 'ਪ੍ਰਸ਼ਾਸਨ ਨਿਯੰਤਰਣ',
    about_us: 'ਸਾਡੇ ਬਾਰੇ',
    citizen_mode: 'ਨਾਗਰਿਕ ਮੋਡ',
    authority_mode: 'ਅਥਾਰਟੀ ਡੈਸ਼ਬੋਰਡ',
    sos_button: 'ਐਮਰਜੈਂਸੀ SOS',
    system_operational: 'ਸਿਸਟਮ ਚਾਲੂ ਹੈ',
    high_risk_areas: 'ਉੱਚ ਖਤਰੇ ਵਾਲੇ ਖੇਤਰ',
    active_alerts: 'ਸਰਗਰਮ ਚੇਤਾਵਨੀਆਂ',
    view_live_risk: 'ਲਾਈਵ ਖਤਰਾ ਨਕਸ਼ਾ ਦੇਖੋ',
    predict_prepare_protect: 'ਭਵਿੱਖਬਾਣੀ. ਤਿਆਰੀ. ਸੁਰੱਖਿਆ.',
    search_location_placeholder: 'ਭਾਰਤੀ ਸ਼ਹਿਰ, ਪਿੰਡ ਜਾਂ ਰਾਜ ਖੋਜੋ...',
    check_risk: 'ਆਪਣਾ ਖਤਰਾ ਚੈੱਕ ਕਰੋ',
    find_shelter: 'ਸੁਰੱਖਿਅਤ ਪਨਾਹਗਾਹ ਲੱਭੋ',
    plan_evacuation: 'ਨਿਕਾਸੀ ਰਸਤਾ ਯੋਜਨਾ',
    report_hazard: 'ਖਤਰੇ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',
    hero_title: 'ਭਵਿੱਖਬਾਣੀ. ਤਿਆਰੀ. ਸੁਰੱਖਿਆ. ਅਚਾਨਕ ਹੜ੍ਹ ਚੇਤਾਵਨੀ ਪ੍ਰਣਾਲੀ',
    hero_subtitle: 'ਪਹਾੜੀ ਖੇਤਰਾਂ ਵਿੱਚ ਰੀਅਲ-ਟਾਈਮ ਅਚਾਨਕ ਹੜ੍ਹ ਦੀ ਭਵਿੱਖਬਾਣੀ ਅਤੇ ਐਮਰਜੈਂਸੀ ਪ੍ਰਬੰਧਨ।',
    live_status: 'ਲਾਈਵ ਸਿਸਟਮ ਸਥਿਤੀ',
    rainfall: 'ਮੀਂਹ',
    river_level: 'ਨਦੀ ਦਾ ਪੱਧਰ',
    soil_moisture: 'ਮਿੱਟੀ ਦੀ ਨਮੀ',
    current_risk: 'ਮੌਜੂਦਾ ਖਤਰਾ',
    danger_near_you: 'ਤੁਹਾਡੇ ਨੇੜੇ ਖਤਰਾ',
    nearest_shelter: 'ਸਭ ਤੋਂ ਨੇੜਲੀ ਸੁਰੱਖਿਅਤ ਪਨਾਹਗਾਹ',
    recommended_route: 'ਸਿਫਾਰਸ਼ ਕੀਤਾ ਸੁਰੱਖਿਅਤ ਰਸਤਾ',
    navigate_shelter: 'ਸੁਰੱਖਿਅਤ ਪਨਾਹਗਾਹ ਵੱਲ ਜਾਓ',
    download_report: 'ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ (PDF)',
    broadcast_alert: 'ਐਮਰਜੈਂਸੀ ਚੇਤਾਵਨੀ ਜਾਰੀ ਕਰੋ',
    digital_twin_heading: 'ਪਿੰਡ ਢਾਂਚਾ ਡਿਜੀਟਲ ਟਵਿਨ ਅਤੇ ਹੜ੍ਹ ਸਿਮੂਲੇਸ਼ਨ',
    history_heading: 'ਇਤਿਹਾਸਕ ਹੜ੍ਹ ਸਮਾਂ-ਰੇਖਾ ਅਤੇ AI ਮਾਡਲ ਜਾਂਚ',
  },
  ne: {
    brand_subtitle: 'स्मार्ट बाढी र मौसम पूर्वसूचना प्रणाली',
    home: 'गृह',
    live_map: 'लाइभ जोखिम नक्शा',
    alerts: 'चेतावनीहरू',
    forecast: 'पूर्वानुमान',
    resources: 'स्रोत पोर्टल',
    digital_twin: 'गाउँ डिजिटल ट्विन',
    history: 'ऐतिहासिक प्रमाणीकरण',
    admin: 'प्रशासन नियन्त्रण',
    about_us: 'हाम्रो बारेमा',
    citizen_mode: 'नागरिक मोड',
    authority_mode: 'प्राधिकरण ड्यासबोर्ड',
    sos_button: 'आपतकालीन SOS',
    system_operational: 'प्रणाली कार्यशील छ',
    high_risk_areas: 'उच्च जोखिम क्षेत्रहरू',
    active_alerts: 'सक्रिय चेतावनीहरू',
    view_live_risk: 'लाइभ जोखिम नक्शा हेर्नुहोस्',
    predict_prepare_protect: 'पूर्वानुमान। तयारी। सुरक्षा।',
    search_location_placeholder: 'भारतीय शहर, गाउँ वा राज्य खोज्नुहोस्...',
    check_risk: 'आफ्नो जोखिम जाँच्नुहोस्',
    find_shelter: 'सुरक्षित आश्रय खोज्नुहोस्',
    plan_evacuation: 'निकासी मार्ग योजना',
    report_hazard: 'जोखिम रिपोर्ट गर्नुहोस्',
    hero_title: 'पूर्वानुमान। तयारी। सुरक्षा। आकस्मिक बाढी पूर्वसूचना प्रणाली',
    hero_subtitle: 'पहाडी क्षेत्रहरूमा वास्तविक समयमा बाढी पूर्वानुमान र आपतकालीन व्यवस्थापन।',
    live_status: 'लाइभ प्रणाली स्थिति',
    rainfall: 'वर्षा',
    river_level: 'नदीको सतह',
    soil_moisture: 'माटोको ओसिलोपना',
    current_risk: 'वर्तमान जोखिम',
    danger_near_you: 'तपाईं नजिकै जोखिम छ',
    nearest_shelter: 'नजिकैको सुरक्षित आश्रय',
    recommended_route: 'सिफारिस गरिएको सुरक्षित मार्ग',
    navigate_shelter: 'सुरक्षित आश्रयतर्फ जानुहोस्',
    download_report: 'पूर्वानुमान प्रतिवेदन डाउनलोड गर्नुहोस् (PDF)',
    broadcast_alert: 'आपतकालीन चेतावनी जारी गर्नुहोस्',
    digital_twin_heading: 'गाउँ पूर्वाधार डिजिटल ट्विन र बाढी सिमुलेशन',
    history_heading: 'ऐतिहासिक बाढी समयरेखा र AI मोडल प्रमाणीकरण',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>('en');

  const t = (key: string): string => {
    const langDict = translations[language] || translations['en'];
    return langDict[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
